In [10]:
import pandas as pd

In [ ]:
#dataframe
info={
    "name":["Mursalin","shuvo","zia","imtiaz"],
    "cgpa":[3.00,3.10,3.76,3]
}
df=pd.DataFrame(info)
print(df)
df

       name  cgpa
0  Mursalin  3.00
1     shuvo  3.10
2       zia  3.76
3    imtiaz  3.00

       name  cgpa
0  Mursalin  3.00
1     shuvo  3.10
2       zia  3.76
3    imtiaz  3.00

In [20]:
#series
s=pd.Series([1,2,3,4,5])
# print(s)
# print(s[0])

age=pd.Series([22,23,45,33],index=["shuvo","mursalin","zia","imtiaz"])
age
print(age["zia"])

45

In [44]:
#series   properties,homogenous
s1=pd.Series([1,2,3,45])
s1[0]=100
print(s1)
s1.drop(0, inplace=True)
print(len(s1))

0    100
1      2
2      3
3     45
dtype: int64
3

In [48]:
s1=pd.Series([1,2,3,45])

s2 = s1.drop(0)   # নতুন series

# check original series size
print("\nOriginal series still has size:", len(s1))

Original series still has size: 4

In [52]:
#datafrane2
info={
    "name":["adam","Eve","Bob"],
    "age":[23,24,26],
    "gpa":[9.5,9.7,9.3]

}
df=pd.DataFrame(info)
print(df)

   name  age  gpa
0  adam   23  9.5
1   Eve   24  9.7
2   Bob   26  9.3

In [56]:
df=pd.DataFrame([["Adam",23],["Bob",44],["shuvo",66]],columns=["name","age"])
df

    name  age
0   Adam   23
1    Bob   44
2  shuvo   66

In [61]:
 df=pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [64]:
#methods
df.head()
df.tail()
df.sample()  #  random  row

   id  name  age country   gender   income
3   3  Alex  NaN     USA  Unknown  47000.0

In [70]:
# df.info()
# df.shape
df.describe()
df.nunique()

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64

In [ ]:
df=pd.read_csv()

In [134]:
#selcting  dada 
# df[["country","income"]]
#row
#df.loc[2]  #  specfic  row
#df.loc[0:2]  #  specfic  row slice
#df.iloc[2]
#df.iloc[0:2]
# df.loc[0:2,["age","gender"]]
# df.iloc[0:3,2]
# df.iloc[:,1:5]  #  print  colum  1to  5   and  all row
# df.at[0,"name"]
# df.iat[0,1]
# df.loc[0, 'city'] = 'Dhaka'
# # df["name"]
# print(df.index)
# names=df["name"]
# names[0]="shuvo"
# n=df["name"].copy()
# names[0]="sljhlh"
# df

C:\Users\progr\AppData\Local\Temp\ipykernel_10296\2232371951.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  names[0]="sljhlh"

    id      name   age country   gender   income   city
0    1    sljhlh  29.0     USA     Male  55000.0  Dhaka
1    1  Mursalin  29.0     USA     Male  55000.0    NaN
2    2  Mursalin   NaN  Canada   Female  62000.0    NaN
3    3  Mursalin   NaN     USA  Unknown  47000.0    NaN
4    4  Mursalin  34.0   Spain   Female      NaN    NaN
5    5  Mursalin  27.0   China     Male  51000.0    NaN
6    6  Mursalin  45.0   India   Female  73000.0    NaN
7    7  Mursalin  38.0     NaN     Male  68000.0    NaN
8    8  Mursalin  29.0     USA   Female  62000.0    NaN
9    9  Mursalin   NaN  Mexico     Male  45000.0    NaN
10  10  Mursalin  31.0     USA      NaN  58000.0    NaN

In [110]:
life_expectancy_rate=pd.read_csv("Life Expectancy Data (1).csv")
life_expectancy_rate.head(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
5,Afghanistan,2010,Developing,58.8,279.0,74,0.01,79.679367,66.0,1989,...,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,Afghanistan,2009,Developing,58.6,281.0,77,0.01,56.762217,63.0,2861,...,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,Afghanistan,2008,Developing,58.1,287.0,80,0.03,25.873925,64.0,1599,...,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,Afghanistan,2007,Developing,57.5,295.0,82,0.02,10.910156,63.0,1141,...,63.0,6.73,63.0,0.1,369.835796,26616792.0,19.0,19.1,0.415,8.4
9,Afghanistan,2006,Developing,57.3,295.0,84,0.03,17.171518,64.0,1990,...,58.0,7.43,58.0,0.1,272.563770,2589345.0,19.2,19.3,0.405,8.1

In [166]:
#filter
d1=pd.read_csv("employee_data.csv")
d = pd.DataFrame(d1)
#d[d["Salary"]>50000]
# d[(d["Salary"]>50000)  & ( d["Department"]=="IT")]
#d[(d["Salary"]>70000) ][["ID","Age"]]
api_data=d[(d["Salary"]>70000) ][["ID","Age"]]
#api_data.iloc[0]  #  this measns current array  index  0 
api_data.loc[3]  #  this measns only  previous  index  not   update  if  we  want  print  then  write  only previous  index  

#print(api_data)
d.query("ID"==1)

ValueError: expr must be a string to be evaluated, <class 'bool'> given

In [167]:
d.query("ID==1")

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000